### ISSUE TITLE
Assign me, I will Add content for DSA, operating systems, Computer Networks and other content too.

### ISSUE THREAD

**Issue by SAQLAINAP** [b0sc/college#1]
# Want to add More Concepts

### programs, flowcharts and diagrams as per the need.

**Comment by SAQLAINAP** [comment]
@axyut @BIIJESH Assign this to me, i could add quality content

**Comment by axyut** [comment]
Hi, when we open issues you can then comment to get them assigned to you, please do not open issues to ask for assignment. I'll close this issue now.
