### ISSUE TITLE
Create a Basic API structure!

### ISSUE THREAD

**Issue by axyut** [b0sc/college#6]
- make changes in c/capi folder based on the task in c/README.md
- use PR template in docs/ when creating a PR

**Comment by leyuskckiran1510** [comment]
@axyut can I use [PB](https://github.com/leyuskckiran1510/peanut-butter) a mini web framework written in C (by me), as it has very small footprint and usage for example.
```c


#include "peanut_butter.h"

ROUTED(status){
    if(is_method("GET")){
        return render_raw_text("{\"status\": \"running\"}");
    }
    return render_404("htmls/404.html");
}

int main(void){
    URL("/status",status);
    return server_run("1234");
}

```

**Comment by axyut** [comment]
You can additionally include it, but to complete the issue, you'll have to implement with everything that is inbuilt and default even if it is harder or uncommon.

**Comment by leyuskckiran1510** [comment]
okay, I will implement with stdlibs for now
